version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=balancer
      - POSTGRES_PASSWORD=balancer
      - POSTGRES_DB=balancer_dev
    ports:
    - "5432:5432"
  backend:
    image: balancer-backend
    build:
      context: server
      dockerfile: Dockerfile.prod 
    ports:
      - "8000:8000"
    env_file:
      - ./config/env/env.dev
    depends_on:
      - db
  frontend:
    image: balancer-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=balancer-frontend
    ports:
        - "3000:3000"
    environment:
        - CHOKIDAR_USEPOLLING=true
        # - VITE_API_BASE_URL=https://balancertestsite.com/
    volumes:
        - "./frontend:/usr/src/app:delegated"
        - "/usr/src/app/node_modules/"
    depends_on:
      - backend

volumes:
  postgres_data: