version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=balancer
      - POSTGRES_PASSWORD=balancer
      - POSTGRES_DB=balancer_dev
  backend:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./config/env/env.dev
    depends_on:
      - db
  frontend:
    image: balancer-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
      args:
        - IMAGE_NAME=balancer-frontend
        - FRONTEND_VERSION=0.0.1
    ports:
        - "3000:3000"
    environment:
        - CHOKIDAR_USEPOLLING=true
    volumes:
        - "./frontend:/usr/src/app:delegated"
        - "/usr/src/app/node_modules/"
    depends_on:
      - backend

volumes:
  postgres_data: