version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
<<<<<<< HEAD
    env_file:
<<<<<<< HEAD
      - ./config/env/env.prod.db
=======
      - ./config/env/.env.prod.db
>>>>>>> ac68347c12ced724206112843623ee8c515bd3ad
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    command: gunicorn balancer_backend.wsgi:application --bind 0.0.0.0:8000
=======
    environment:
      - POSTGRES_USER=balancer
      - POSTGRES_PASSWORD=balancer
      - POSTGRES_DB=balancer_dev
>>>>>>> 5d9968afe8f5ab373ab0379485cea79ba3253193
    ports:
    - "5432:5432"
  backend:
    image: balancer-backend
    build:
      context: server
      dockerfile: Dockerfile.prod 
    ports:
      - "8000:8000"
    env_file:
<<<<<<< HEAD
      - ./config/env/env.prod
=======
      - ./config/env/env.dev
>>>>>>> 5d9968afe8f5ab373ab0379485cea79ba3253193
    depends_on:
      - db
<<<<<<< HEAD
=======
  frontend:
    image: balancer-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - IMAGE_NAME=balancer-frontend
    ports:
        - "3000:3000"
    environment:
        - CHOKIDAR_USEPOLLING=true
        # - VITE_API_BASE_URL=https://balancertestsite.com/
    volumes:
        - "./frontend:/usr/src/app:delegated"
        - "/usr/src/app/node_modules/"
    depends_on:
      - backend
>>>>>>> ac68347c12ced724206112843623ee8c515bd3ad

volumes:
  postgres_data: