apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
# https://stackoverflow.com/questions/64178370/custom-nginx-conf-from-configmap-in-kubernetes
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  1024;
    }
    http {
      include /etc/nginx/mime.types;
      error_log  /var/log/nginx/error_log;
      access_log /var/log/nginx/access_log;
      server {
        listen       80;
        listen  [::]:80;
        server_name  {{ .Values.nginx.serverName }};
    
        location /access_log {
            alias /var/log/nginx/access_log;
        }
        location /error_log {
            alias /var/log/nginx/error_log;
        }
        
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
  
        #error_page  404              /404.html;
  
        # redirect server error pages to the static page /50x.html
        #
        #error_page   500 502 503 504  /50x.html;
        #location = /50x.html {
        #    root   /usr/share/nginx/html;
        
        #}
      }
    }
    
